[package]
name = "poe_gem_parser"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "PoE gem parser written in Rust"

[dependencies]
pest_derive = "2.7.14"
pest = "2.7.14"
anyhow = "1.0.91"
thiserror = "2.0.3"